#!/bin/bash

# setup temporary variables
BASE_DIR=$(pwd)

# load recipe informations
source recipes/$RECIPE/recipe
source distros/$DISTRO

echo
echo "##"
echo "# RECIPE: $RECIPE"
echo "# DISTRO: $DISTRO"
echo "#"
echo

START_TIME=$(date +%s)

# load build core
source core/config
source core/variables
source core/helpers

# prepare target dir
mkdir -p $ROOTFS_DIR
mkdir -p $LOG_DIR

# clean old logs
rm -f $LOGS_DIR/*.log

if [ ! -f $ROOTFS_DIR/bin/bash ] || [ -n "${REBUILD}" ]; then
  # prepare distro
  run do_distro
fi

# initialize the container
run do_container

# move specified files into rootfs
run do_files

# run build steps
for step in $build_steps; do
  # only run existing functions
  if declare -f $step &> /dev/null; then
    container_run $step
  fi
done

echo
echo "Build of \"$RECIPE\" completed after $(expr $(date +%s) - $START_TIME) seconds."