#!/bin/bash

# format: opts:step
#
# opts
#   0 = native
#   1 = container
#
# step
#   name of the step
#

build_steps=" \
  0:do_distro \
  1:do_depends \
  1:do_prepare \
  1:do_compile \
  1:do_install \
  1:do_cleanup \
  0:do_image \
"
